### PR TITLE
typescriptify, cleanup a bit

### PR DESCRIPTION
**Pull request by yelsayd**
This PR keeps the same functionality, but with the code rewritten in Typescript, and built into Javascript just for comparison. If you decide to keep the Typescript code, you should remove the Javascript file and add it to the gitignore.

Other cleanups done here are:
- *Some* var cleanups to const. Some is keyword here, there's still a lot to be done.
- Removed initialize methods, added their body into the constructor. This way you don't need the initialize flag.
- Same thing for build_lines. I kept the method, turning it to private, and calling it from the constructor, since this looks like it'll be done only once during construction.
- Used `Immutable.List` consistently for all `lines` properties, which was a regular array for two of the classes.

With this change, you'll need to have npm installed, then you can do `npm install` inside the directory once to get all the dependencies (typescript and immutable), then you can do `npm run build` on each change to transpile `main.ts` to `main.js`. There are some tools to do the transpile automatically on save so that you can iterate on the file quickly, we can look into that later.

Also, I highly recomment using vscode for this work, you get a lot out of the box.

### CODE REVIEW

**Comment by Ahmed-Salama** [comment]
Removing the initialize method will add performance overhead. The reason is since everything is immutable, `Entity.copy()` implementation initialize a new object of the same type (Calling the constructor) and copy unchanged properties over. `Initialize()` is the placeholder for logic that should be done only once (example: `build_lines()`).

Better way to go might be to negact the initialize flag in the constructor. That way a client creating an instance doesn't need to worry about passing it set to true. Maybe call it "PartialConstruction" and only `Entity.copy()` set it to true.

Maybe rename initialize to something more meaningful. "bootstrap" maybe?

**Comment by Ahmed-Salama** [comment]
Maybe rename

**Review by Ahmed-Salama — CHANGES_REQUESTED** [review]
Readd the initialize method.

**Comment by yelsayd** [comment]
I see. I still don't get the whole copy business, and the use of immutables. I'm not sure that's a good idea for a physics engine from a performance perspective, but that's a discussion for another time.

You'll need to make the changes in the typescript file not the javascript file btw. :)

**Comment by Ahmed-Salama** [comment]
That would make for an interesting merge resolution :P Approving the changes now.

**Review by Ahmed-Salama — APPROVED** [review]

**Pull request merged**
